### ISSUE TITLE
change some value when the other keep unchanged？

### ISSUE THREAD

**Issue by helloyan** [kopera/erlang-gpio#1]
can it change some value when the other keep unchanged?

**Comment by asabil** [comment]
Yes, you just need to open separate lines. If you need to control two separate GPIO lines independently from each another, you can call `open_lines` multiple times.

**Comment by helloyan** [comment]
How can I monitor both the falling edge and rising edge at the same time? open mulitple times?

**Comment by asabil** [comment]
Yes you can, use `gpio:open_line_events/5` and specify both `rising_edge` and `falling_edge` for the EventFlags: https://hexdocs.pm/gpio/gpio.html#open_line_events/5
